<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.cqjtu</groupId>
    <artifactId>dpta</artifactId>
    <packaging>pom</packaging>
    <version>1.0-SNAPSHOT</version>

    <modules>
        <module>start</module>
        <module>dpta-web</module>
        <module>dpta-dao</module>
        <module>dpta-service</module>
        <module>dpta-api</module>
        <module>dpta-common</module>
        <module>dpta-mall</module>
        <module>dpta-gateway</module>
    </modules>

    <properties>
        <maven.compiler.source>17</maven.compiler.source>
        <maven.compiler.target>17</maven.compiler.target>
        <java.version>17</java.version>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
        <swagger.version>2.7.0</swagger.version>

        <spring-boot.version>3.5.10</spring-boot.version>
        <spring-cloud.version>2025.0.1</spring-cloud.version>
        <spring-cloud-alibaba.version>2025.0.0.0</spring-cloud-alibaba.version>
<!--        <dubbo.version>2.7.8</dubbo.version>-->
        <mybatis-plus.version>3.5.15</mybatis-plus.version>
        <druid.version>1.2.27</druid.version>
        <fastjson2.version>2.0.59</fastjson2.version>
    </properties>

<!--    <repositories>-->
<!--        <repository>-->
<!--            <id>jcenter-snapshots</id>-->
<!--            <name>jcenter</name>-->
<!--            <url>https://jcenter.bintray.com/</url>-->
<!--        </repository>-->
<!--    </repositories>-->

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-dependencies</artifactId>
                <version>${spring-boot.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-dependencies</artifactId>
                <version>${spring-cloud.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <!--spring cloud alibaba-->
            <dependency>
                <groupId>com.alibaba.cloud</groupId>
                <artifactId>spring-cloud-alibaba-dependencies</artifactId>
                <version>${spring-cloud-alibaba.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>com.baomidou</groupId>
                <artifactId>mybatis-plus-bom</artifactId>
                <version>${mybatis-plus.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>

<!--            &lt;!&ndash; Dubbo Dependencies &ndash;&gt;-->
<!--            <dependency>-->
<!--                <groupId>org.apache.dubbo</groupId>-->
<!--                <artifactId>dubbo-dependencies-bom</artifactId>-->
<!--                <version>${dubbo.version}</version>-->
<!--                <type>pom</type>-->
<!--                <scope>import</scope>-->
<!--                <exclusions>-->
<!--                    <exclusion>-->
<!--                        <groupId>org.springframework</groupId>-->
<!--                        <artifactId>spring-framework-bom</artifactId>-->
<!--                    </exclusion>-->
<!--                </exclusions>-->
<!--            </dependency>-->

<!--            <dependency>-->
<!--                <groupId>org.apache.dubbo</groupId>-->
<!--                <artifactId>dubbo-spring-boot-starter</artifactId>-->
<!--                <version>${dubbo.version}</version>-->
<!--            </dependency>-->

<!--            <dependency>-->
<!--                <groupId>org.apache.dubbo</groupId>-->
<!--                <artifactId>dubbo-spring-boot-actuator</artifactId>-->
<!--                <version>${dubbo.version}</version>-->
<!--            </dependency>-->

<!--            <dependency>-->
<!--                <groupId>org.apache.dubbo</groupId>-->
<!--                <artifactId>dubbo</artifactId>-->
<!--                <version>${dubbo.version}</version>-->
<!--                <exclusions>-->
<!--                    <exclusion>-->
<!--                        <groupId>org.springframework</groupId>-->
<!--                        <artifactId>spring-context</artifactId>-->
<!--                    </exclusion>-->
<!--                </exclusions>-->
<!--            </dependency>-->

            <!--swagger-->
            <dependency>
                <groupId>io.springfox</groupId>
                <artifactId>springfox-swagger2</artifactId>
                <version>${swagger.version}</version>
            </dependency>
            <!--swagger ui-->
            <dependency>
                <groupId>io.springfox</groupId>
                <artifactId>springfox-swagger-ui</artifactId>
                <version>${swagger.version}</version>
            </dependency>

            <dependency>
                <groupId>com.alibaba.fastjson2</groupId>
                <artifactId>fastjson2</artifactId>
                <version>${fastjson2.version}</version>
            </dependency>

            <dependency>
                <groupId>com.alibaba.fastjson2</groupId>
                <artifactId>fastjson2-extension-spring6</artifactId>
                <version>${fastjson2.version}</version>
            </dependency>

            <dependency>
                <groupId>com.alibaba</groupId>
                <artifactId>druid-spring-boot-starter</artifactId>
                <version>${druid.version}</version>
                <scope>compile</scope>
            </dependency>

            <!--            <dependency>-->
            <!--                <groupId>org.springframework.boot</groupId>-->
            <!--                <artifactId>spring-boot-devtools</artifactId>-->
            <!--                <scope>runtime</scope>-->
            <!--                <optional>true</optional>-->
            <!--            </dependency>-->

        </dependencies>
    </dependencyManagement>
</project>