spring:
  cache:
    type: redis
    redis:
      time-to-live: 3600000
      key-prefix: dpta_cache_
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 132135138zsl
    url: jdbc:mysql://localhost:3306/dpta?serverTimezone=Asia/Shanghai
  redis:
    host: 124.70.47.130
    password: 132135138zsl
  jpa:
    show-sql: true
  data:
    mongodb:
      uri: mongodb://mumu:132135138zsl@localhost/dpta

server:
  port: 8081
  error:
    path: /basic/error


#swagger:
#  enable: true

#logging:
#  level:
#    root: debug

mybatis-plus:
  #  configuration:
  #    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: deleted  # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
  type-enums-package: com.cqjtu.dpta.dao.entity.emus

elasticsearch:
  host: localhost
  port: 9200

dpta:
  mall-url: http://localhost:8080
#  auto-gen: true
#  build-es: true
