spring:
  cache:
    type: redis
    redis:
      time-to-live: 3600000
      key-prefix: dpta_cache
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 132135138zsl
    #    url: jdbc:mysql://10.61.54.95:3306/dpta?serverTimezone=Asia/Shanghai
    url: jdbc:mysql://localhost:3306/dpta?serverTimezone=Asia/Shanghai
  redis:
    host: 192.168.83.131


server:
  port: 8080
  error:
    path: /basic/error


swagger:
  enable: false

#logging:
#  level:
#    root: debug
#mybatis-plus:
#  mapper-locations: classpath:mapper/*.xml
