server:
  port: 8082

spring:
  thymeleaf:
    cache: false
  datasource:
    name: newbee-mall-datasource
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.237.142:3306/dpta?useUnicode=true&serverTimezone=Asia/Shanghai&characterEncoding=utf8&autoReconnect=true&useSSL=false&allowMultiQueries=true&allowPublicKeyRetrieval=true
    username: root
    password: Ht@62628816
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      pool-name: hikariCP
      max-lifetime: 30000
      connection-timeout: 30000
      connection-test-query: SELECT 1

# mybatis config
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml

dpta:
  url: http://localhost:8081
  admin-front-url: http://localhost:9528/admin
  distr-front-url: http://localhost:9529/distr

# spring config
#spring:
#  cloud:
#    nacos:
#      config:
#        import-check:
#          enabled: false