spring:
  cache:
    type: redis
    redis:
      time-to-live: 3600000
      key-prefix: dpta_cache
  redis:
#    host: 192.168.83.131
    host: 124.70.47.130
    password: 132135138zsl

  elasticsearch:
    rest:
      uris: http://192.168.83.131:9200
#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: admin
#    password: admin

elasticsearch:
  host: 192.168.83.131
  port: 9200

server:
  port: 8089

#logging:
#  level:
#    root: debug
