spring:
  cache:
    type: redis
    redis:
      time-to-live: 3600000
      key-prefix: dpta_cache
  redis:
    host: 192.168.83.131
  elasticsearch:
    rest:
      uris: http://192.168.83.131:9200

elasticsearch:
  host: 192.168.83.131
  port: 9200

server:
  port: 8089

#logging:
#  level:
#    root: debug
